# Generated by Django 3.1.5 on 2021-01-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='수정일시'),
        ),
    ]
